In [67]:
import torch
import torch.nn as nn
import torch.optim as optim

In [33]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [34]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [35]:
df.shape

(569, 33)

In [36]:
df.drop(columns = ["id","Unnamed: 32"],inplace = True)

In [37]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [38]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0], test_size = 0.2)

In [39]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [40]:
y_train

427    B
450    B
191    B
142    B
369    M
      ..
256    M
468    M
517    M
480    B
151    B
Name: diagnosis, Length: 455, dtype: object

In [68]:
x_train_tensor.shape

torch.Size([455, 30])

In [69]:
y_train_tensor.shape

torch.Size([455])

In [70]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [71]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [72]:
#create model class
class MySimpleNN(nn.Module):
  def __init__(self,features):
    super().__init__()
    self.linear  = nn.Linear(features,1)
    self.sigmoid = nn.Sigmoid()
  def forward(self, x):
    out = self.linear(x)
    out = self.sigmoid(out)
    return out

In [73]:
learning_rate = 0.1
epochs = 30

In [74]:
loss_fnc = nn.BCELoss()

In [76]:
optim = torch.optim.SGD(model.parameters(),lr = learning_rate)

In [77]:
#create model
model = MySimpleNN(x_train_tensor.shape[1])
# define loop
for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(x_train_tensor.float()) # Ensure input is float

  #loss calculate
  loss = loss_fnc(y_pred, y_train_tensor.float().view(-1,1)) # Ensure target is float

  optim.zero_grad()
  #backward pass
  loss.backward()

  #update weights
  optim.step()
  #zero gradients

  print(f"epoch : {epoch+1}, loss : {loss.item()}")

epoch : 1, loss : 0.6504702568054199
epoch : 2, loss : 0.6504702568054199
epoch : 3, loss : 0.6504702568054199
epoch : 4, loss : 0.6504702568054199
epoch : 5, loss : 0.6504702568054199
epoch : 6, loss : 0.6504702568054199
epoch : 7, loss : 0.6504702568054199
epoch : 8, loss : 0.6504702568054199
epoch : 9, loss : 0.6504702568054199
epoch : 10, loss : 0.6504702568054199
epoch : 11, loss : 0.6504702568054199
epoch : 12, loss : 0.6504702568054199
epoch : 13, loss : 0.6504702568054199
epoch : 14, loss : 0.6504702568054199
epoch : 15, loss : 0.6504702568054199
epoch : 16, loss : 0.6504702568054199
epoch : 17, loss : 0.6504702568054199
epoch : 18, loss : 0.6504702568054199
epoch : 19, loss : 0.6504702568054199
epoch : 20, loss : 0.6504702568054199
epoch : 21, loss : 0.6504702568054199
epoch : 22, loss : 0.6504702568054199
epoch : 23, loss : 0.6504702568054199
epoch : 24, loss : 0.6504702568054199
epoch : 25, loss : 0.6504702568054199
epoch : 26, loss : 0.6504702568054199
epoch : 27, loss : 0.6504702568054199
epoch : 28, loss : 0.6504702568054199
epoch : 29, loss : 0.6504702568054199
epoch : 30, loss : 0.6504702568054199

In [80]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor.float()) # Cast input to float
#print(y_pred)
  y_pred_class = (y_pred > 0.9).float()
  print(y_pred_class)
  acc = (y_pred_class == y_test_tensor.float()).float().mean() # Cast target to float
  print(acc.item())

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
0.6754385828971863

In [18]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0